/* 
 * 
 */ 
package parser;

/**
 * Defines the class 'BTypeFile' that represents a single text file generated by
 * Daemon and automatically stored in the Inbox
 *
 * @author David García
 */
public class BTypeFile {

    private String header = new String();
    private String priority = new String();
    private String destinationTypeB = new String();
    private String origin = new String();
    private String dblsig = new String();
    private String msgid = new String();
    private String subject = new String();
    private String smi = new String();
    private String faxHeader = new String();
    private String texto = new String();
    private String attachments = new String();

    /**
     * Constructor, creates an objetc of class BTypeFile.
     */
    public BTypeFile() {
    }

    public void setHeader(String header) {
        this.header = header.trim();
    }

    public void setPriority(String priority) {
        this.priority = priority.trim();
    }

    public void setDestinationTypeB(String destinationTypeB) {
        this.destinationTypeB = destinationTypeB.trim();
    }

    public void setOrigin(String origin) {
        this.origin = origin.trim();
    }

    public void setDblsig(String dblsig) {
        this.dblsig = dblsig.trim();
    }

    public void setMsgid(String msgid) {
        this.msgid = msgid.trim();
    }

    public void setSubject(String subject) {
        this.subject = subject.trim();
    }

    public void setSmi(String smi) {
        this.smi = smi.trim();
    }

    public void setFaxHeader(String faxHeader) {
        this.faxHeader = faxHeader.trim();
    }

    public void setText(String text) {
        String t = text;
        t = t.trim();
        this.texto = t.replace("\n", "<br>");
    }

    public void setAttachments(String attachments) {
        this.attachments = attachments.trim();
    }

    public String getHeader() {
        return header;
    }

    public String getPriority() {
        return priority;
    }

    public String getDestinationTypeB() {
        return destinationTypeB;
    }

    public String getOrigin() {
        return origin;
    }

    public String getDblsig() {
        return dblsig;
    }

    public String getMsgid() {
        return msgid;
    }

    public String getSubject() {
        return subject;
    }

    public String getSmi() {
        return smi;
    }

    public String getFaxHeader() {
        return faxHeader;
    }

    public String getText() {
        return texto;
    }

    public String getAttachments() {
        return attachments;
    }

    @Override
    public String toString() {

        return this.texto;
    }
}